// Copy from the design (Total Care Patient App.dc.html). The Arabic is a draft in
// Egyptian dialect and still needs review by a native speaker.
const en = {
  switch_lang: 'العربية', welcome_title: 'Care that comes home', welcome_body: "Rent home-care devices, follow every delivery and talk to our team whenever you need us. We're here for you and your family.", continue: 'Continue', terms: "We'll text you a 4-digit code to sign in.",
  greet: 'Good morning, Nadia', greet_sub: "Here's your care at a glance.", out_for_delivery: 'Your order is on its way', arriving: 'Arriving today, 4–6 PM', active_rental: 'Active rental', day_of: 'Day 12 of 30', filter_check: 'Filter check · Sat 26 Sep', renew: 'Renew',
  qa_rent: 'Rent a device', qa_visit: 'Book a visit', qa_guides: 'How-to videos', qa_chat: 'Chat with us', guide_eyebrow: 'Picked for you', guide_title: 'Setting up your oxygen concentrator', guide_meta: 'Video · 3 min',
  tab_home: 'Home', tab_shop: 'Rent & buy', tab_orders: 'Orders', tab_chat: 'Support', tab_profile: 'Profile',
  shop_title: 'Rent & buy', search: 'Search devices and supplies', cat_all: 'All', cat_resp: 'Respiratory', cat_mob: 'Mobility', cat_diab: 'Diabetes', cat_mon: 'Monitoring', rent: 'Rent', buy: 'Buy', per_mo: '/mo', devices: 'items',
  p_o2: 'Oxygen concentrator 5L', p_cpap: 'CPAP machine', p_neb: 'Compressor nebulizer', p_wc: 'Folding wheelchair', p_bed: 'Electric home-care bed', p_gluc: 'Glucose meter kit', p_strips: 'Glucose test strips · 50', p_oxi: 'Fingertip pulse oximeter',
  pd_o2: 'A quiet 5-litre concentrator for oxygen therapy at home. Our technician delivers it, sets it up and shows you and your family exactly how to use it.', pd_photo: 'Product photo', pd_duration: 'Rental period', d_1w: '1 week', d_1m: '1 month', d_3m: '3 months', save: 'Save 12%', pd_includes: "What's included", inc1: 'Home setup by a certified technician', inc2: '24/7 phone and chat support', inc3: 'Free swap if anything goes wrong', pd_free: 'Free delivery & setup in Cairo and Giza', deposit: 'Refundable deposit', add_cart: 'Add to cart', added: 'Added to your cart',
  cart_title: 'Your cart', empty: 'Your cart is empty.', deliver_to: 'Deliver to', address: '12 Road 9, Maadi, Cairo', change: 'Change', slot: 'Delivery', slot_val: 'Tomorrow, 10 AM – 1 PM', payment: 'Payment', pay_cod: 'Cash on delivery', pay_card: 'Card on delivery', pay_insta: 'InstaPay', subtotal: 'Subtotal', delivery_fee: 'Delivery & setup', free: 'Free', total: 'Total on delivery', place: 'Place order', placed: 'Order placed. We will text you updates.', rental: 'Rental', purchase: 'Purchase',
  track_title: 'Order TC-20417', eta_l: 'Estimated arrival', eta: 'Today, 4–6 PM', st1: 'Order confirmed', st2: 'Packed at our warehouse', st3: 'Out for delivery', st4: 'Setup at your home', st4_time: '4–6 PM', courier: 'Mahmoud · your technician', courier_sub: 'Delivers, installs and trains you', prep_title: 'Before Mahmoud arrives', prep_body: 'Watch the 3-minute setup video so you know what to expect.',
  visit_title: 'Book a home visit', visit_sub: 'A Total Care specialist comes to you.', svc1: 'Device setup & training', svc1p: 'Free with your rental', svc2: 'Nurse home visit', svc3: 'Device maintenance', pick_day: 'Choose a day', pick_time: 'Choose a time', confirm_visit: 'Confirm visit', booked: "Visit booked. We'll remind you the day before.",
  chat_agent: 'Mariam', chat_role: 'Total Care support · online', today: 'Today', type: 'Write a message', typing: 'Mariam is typing…', qr1: 'Book a technician', qr2: "Where's my order?", qr3: 'Talk to a nurse',
  m1: "Hi Nadia, I'm Mariam from Total Care. How can I help you today?", m2: 'The oxygen machine keeps beeping. Is that normal?', m3: 'A short beep when it starts is normal. If it keeps going, check that the filter is pushed all the way in. This 2-minute video shows how:', video_title: 'Checking the filter', video_meta: 'Video · 2 min', reply: "Thanks, Nadia. I'm on it, give me a moment.",
  a11y_back: 'Back', a11y_call: 'Call', a11y_chat: 'Chat', a11y_send: 'Send', a11y_cart: 'Cart', a11y_notifications: 'Notifications', a11y_decrease: 'Decrease', a11y_increase: 'Increase',
};

export type Strings = typeof en;
export type StringKey = keyof Strings;

const ar: Strings = {
  switch_lang: 'English', welcome_title: 'رعاية تصل إلى بيتك', welcome_body: 'استأجر أجهزة الرعاية المنزلية، تابع كل طلب، وكلّم فريقنا في أي وقت تحتاجنا. إحنا معاك ومع أسرتك.', continue: 'متابعة', terms: 'هنبعت لك كود من 4 أرقام لتسجيل الدخول.',
  greet: 'صباح الخير يا نادية', greet_sub: 'كل ما يخص رعايتك في مكان واحد.', out_for_delivery: 'طلبك في الطريق', arriving: 'يوصل النهارده، 4–6 مساءً', active_rental: 'إيجار حالي', day_of: 'اليوم 12 من 30', filter_check: 'فحص الفلتر · السبت 26 سبتمبر', renew: 'تجديد',
  qa_rent: 'استأجر جهاز', qa_visit: 'احجز زيارة', qa_guides: 'فيديوهات الاستخدام', qa_chat: 'كلّمنا', guide_eyebrow: 'مختار لك', guide_title: 'تركيب جهاز تركيز الأكسجين', guide_meta: 'فيديو · 3 دقائق',
  tab_home: 'الرئيسية', tab_shop: 'إيجار وشراء', tab_orders: 'طلباتي', tab_chat: 'الدعم', tab_profile: 'حسابي',
  shop_title: 'إيجار وشراء', search: 'ابحث عن جهاز أو مستلزمات', cat_all: 'الكل', cat_resp: 'التنفس', cat_mob: 'الحركة', cat_diab: 'السكر', cat_mon: 'القياس', rent: 'إيجار', buy: 'شراء', per_mo: '/شهر', devices: 'منتج',
  p_o2: 'جهاز تركيز الأكسجين 5 لتر', p_cpap: 'جهاز سي باب', p_neb: 'جهاز نيبولايزر', p_wc: 'كرسي متحرك قابل للطي', p_bed: 'سرير طبي كهربائي', p_gluc: 'جهاز قياس السكر', p_strips: 'شرائط قياس السكر · 50', p_oxi: 'جهاز قياس نسبة الأكسجين',
  pd_o2: 'جهاز هادئ بقدرة 5 لتر للعلاج بالأكسجين في البيت. الفنّي بتاعنا بيوصّله ويركّبه ويشرح لك ولأسرتك طريقة استخدامه خطوة بخطوة.', pd_photo: 'Product photo', pd_duration: 'مدة الإيجار', d_1w: 'أسبوع', d_1m: 'شهر', d_3m: '3 شهور', save: 'وفّر 12%', pd_includes: 'يشمل', inc1: 'تركيب في البيت بواسطة فنّي معتمد', inc2: 'دعم بالتليفون والشات 24/7', inc3: 'استبدال مجاني عند أي عطل', pd_free: 'توصيل وتركيب مجاني في القاهرة والجيزة', deposit: 'تأمين مسترد', add_cart: 'أضف للسلة', added: 'اتضاف للسلة',
  cart_title: 'سلتك', empty: 'السلة فاضية.', deliver_to: 'التوصيل إلى', address: '12 شارع 9، المعادي، القاهرة', change: 'تغيير', slot: 'موعد التوصيل', slot_val: 'بكرة، 10 ص – 1 م', payment: 'الدفع', pay_cod: 'كاش عند الاستلام', pay_card: 'كارت عند الاستلام', pay_insta: 'إنستاباي', subtotal: 'المجموع', delivery_fee: 'التوصيل والتركيب', free: 'مجاناً', total: 'الإجمالي عند الاستلام', place: 'تأكيد الطلب', placed: 'تم تأكيد طلبك. هنبعت لك التحديثات.', rental: 'إيجار', purchase: 'شراء',
  track_title: 'طلب TC-20417', eta_l: 'الوصول المتوقع', eta: 'النهارده، 4–6 م', st1: 'تم تأكيد الطلب', st2: 'اتجهز في المخزن', st3: 'خرج للتوصيل', st4: 'التركيب في بيتك', st4_time: '4–6 م', courier: 'محمود · الفنّي بتاعك', courier_sub: 'هيوصّل ويركّب ويشرح لك', prep_title: 'قبل ما محمود يوصل', prep_body: 'شوف فيديو التركيب (3 دقايق) عشان تكون جاهز.',
  visit_title: 'احجز زيارة منزلية', visit_sub: 'متخصص من توتال كير يجيلك البيت.', svc1: 'تركيب وتدريب على الجهاز', svc1p: 'مجاناً مع الإيجار', svc2: 'زيارة تمريض منزلية', svc3: 'صيانة الجهاز', pick_day: 'اختر اليوم', pick_time: 'اختر الوقت', confirm_visit: 'تأكيد الزيارة', booked: 'تم الحجز. هنفكّرك قبلها بيوم.',
  chat_agent: 'مريم', chat_role: 'دعم توتال كير · متصلة', today: 'النهارده', type: 'اكتب رسالة', typing: 'مريم بتكتب…', qr1: 'احجز فنّي', qr2: 'طلبي فين؟', qr3: 'كلّم ممرضة',
  m1: 'أهلاً يا نادية، أنا مريم من توتال كير. أقدر أساعدك في إيه النهارده؟', m2: 'جهاز الأكسجين بيصفّر على طول. ده طبيعي؟', m3: 'صفارة قصيرة وقت التشغيل طبيعية. لو مستمرة، اتأكدي إن الفلتر داخل في مكانه كويس. الفيديو ده بيوضح الطريقة في دقيقتين:', video_title: 'فحص الفلتر', video_meta: 'فيديو · دقيقتين', reply: 'شكراً يا نادية، ثواني وهرد عليكي.',
  a11y_back: 'رجوع', a11y_call: 'اتصال', a11y_chat: 'محادثة', a11y_send: 'إرسال', a11y_cart: 'السلة', a11y_notifications: 'الإشعارات', a11y_decrease: 'تقليل', a11y_increase: 'زيادة',
};

export type Lang = 'en' | 'ar';
export const strings: Record<Lang, Strings> = { en, ar };
